#!/bin/bash 

. ./platform.properties
. ./functions
. ./functions-tomcat

#---------------------------------------------
removeTomcatFiles() {
#---------------------------------------------
  CURDIR=`pwd` 
  if [ ! -z ${TOMCAT_BASE} ]; then
    cd ${TOMCAT_BASE}
    ${RM} -rf *
    if [ $? != 0 ]; then
      printf "ERROR: Error removing data in tomcat base directory ${TOMCAT_BASE}. Aborting.\n"
    else
      printf "INFO: Successfully removed Tomcat files from directory ${TOMCAT_BASE}.\n"
    fi 
  fi
  cd ${CURDIR}
}

#---------------------------------------------
# Main
#---------------------------------------------
stopTomcat
removeTomcatFiles





