#!/bin/bash

. ./platform.properties
. ./functions
. ./functions-httpd
. ./ca/ca.properties

#---------------------------------------------
copyServerCert() {
#---------------------------------------------

  KEY_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-key-no-pin.pem
  P12_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-key.p12
  CERT_FILE=${CA_SSL_SERVER_CERT_DIR}/${SERVER_FQDN}-cert.pem
  CERT_CHAIN=${CA_SSL_SERVER_CERT_DIR}/../${CA_CERT}

  if [ ! -f ${KEY_FILE} ]; then
    printf "ERROR: Key file ${KEY_FILE} does not exist. You must create it first. Check the ca section.\n"
    exit 1 
  fi
  if [ ! -f ${CERT_FILE} ]; then
    printf "ERROR: Certificate file ${CERT_FILE} does not exist. You must create it first. Check the ca section.\n"
    exit 1 
  fi
  if [ ! -f ${CERT_CHAIN} ]; then
    printf "ERROR: Certificate chain file ${CERT_CHAIN} does not exist. Check the ca section.\n"
    exit 1 
  fi

  ${CP} ${KEY_FILE} ${HTTPD_SERVER_KEY_PEM}
  ${CP} ${CERT_FILE} ${HTTPD_SERVER_CERT_PEM}
  ${CP} ${P12_FILE} ${HTTPD_SERVER_KEY_P12}
  ${CP} ${CERT_CHAIN} ${HTTPD_SERVER_CERT_CHAIN_PEM}
}

#---------------------------------------------
modifyHttpdConfig() {
#---------------------------------------------
  #
  # Create a .conf file and place it in the conf.d directory under the HTTPD base
  # This file will be loaded without touching the httpd.conf file
  #

  # First backup existing custom conf file
  if [ -f ${HTTPD_SERVER_CUSTOM_CONF} ]; then
    CURDATE=`${DATE} '+%Y%m%d%H%M'`
    ${CP} -p ${HTTPD_SERVER_CUSTOM_CONF} ${HTTPD_SERVER_CUSTOM_CONF}.bak.${CURDATE}
  fi
  
  HTTPD_SERVER_CERT_PEM_ESCAPED=`escapePath ${HTTPD_SERVER_CERT_PEM}`
  HTTPD_SERVER_KEY_PEM_ESCAPED=`escapePath ${HTTPD_SERVER_KEY_PEM}`
  HTTPD_SERVER_CERT_CHAIN_PEM_ESCAPED=`escapePath ${HTTPD_SERVER_CERT_CHAIN_PEM}`
  
  ${SED} -e "s/%SERVER_FQDN%/${SERVER_FQDN}/g" -e "s/%TOMCAT_HTTPS_PORT%/${TOMCAT_HTTPS_PORT}/g" -e "s/%HTTPD_SERVER_CERT_PEM%/${HTTPD_SERVER_CERT_PEM_ESCAPED}/g" -e "s/%HTTPD_SERVER_KEY_PEM%/${HTTPD_SERVER_KEY_PEM_ESCAPED}/g"   -e "s/%HTTPD_SERVER_CERT_CHAIN_PEM%/${HTTPD_SERVER_CERT_CHAIN_PEM_ESCAPED}/g"   -e "s/%OPENAM_DEPLOYMENT_URI%/${OPENAM_DEPLOYMENT_URI}/g"  ${INSTALL_SCRIPTS_BASE}/templates/httpd-server.conf.TEMPLATE > ${HTTPD_SERVER_CUSTOM_CONF}

}

#---------------------------------------------
# Main
#---------------------------------------------
copyServerCert
modifyHttpdConfig
stopHttpd
startHttpd




