#!/bin/bash

. ./platform.properties
. ./functions
. ./functions-httpd

#---------------------------------------------
generateServerCert() {
#---------------------------------------------
  ${OPENSSL} genrsa -out ${HTTPD_SERVER_KEY_PEM} 2048
  if [ $? != 0 ]; then
    printf "ERROR: Failed to generate server key.\n"
    exitFailure
  fi

  ${OPENSSL} req -new -x509 -key ${HTTPD_SERVER_KEY_PEM} -out ${HTTPD_SERVER_CERT_PEM} -days 3650 -subj "/CN=${SERVER_FQDN}" -sha256
  if [ $? != 0 ]; then
    printf "ERROR: Failed to generate self signed server certificate.\n"
    exitFailure
  fi

  #Convert to .p12
  ${OPENSSL} pkcs12 -export -in ${HTTPD_SERVER_CERT_PEM} -inkey ${HTTPD_SERVER_KEY_PEM} -out ${HTTPD_SERVER_KEY_P12} -name ${SERVER_FQDN} -passout pass:${HTTPD_SERVER_KEY_PIN}
  if [ $? != 0 ]; then
    printf "ERROR: Failed to generate self signed (HTTPD) server certificate.\n"
    exitFailure
  fi

  printf "INFO: Successfully generated server key (${HTTPD_SERVER_KEY_PEM}) and server certificate (${HTTPD_SERVER_CERT_PEM}).\n"
}

#---------------------------------------------
generateServerCertChain() {
#---------------------------------------------
  #${OPENSSL} verify -CAfile ${HTTPD_SERVER_CERT_CHAIN_PEM} ${HTTPD_SERVER_CERT_PEM}
  cat ${HTTPD_SERVER_CERT_PEM} >> ${HTTPD_SERVER_CERT_CHAIN_PEM}
}

#---------------------------------------------
modifyHttpdConfig() {
#---------------------------------------------
  #
  # Create a .conf file and place it in the conf.d directory under the HTTPD base
  # This file will be loaded without touching the httpd.conf file
  #

  # First backup existing custom conf file
  if [ -f ${HTTPD_SERVER_CUSTOM_CONF} ]; then
    CURDATE=`${DATE} '+%Y%m%d%H%M'`
    ${CP} -p ${HTTPD_SERVER_CUSTOM_CONF} ${HTTPD_SERVER_CUSTOM_CONF}.bak.${CURDATE}
  fi
  
  HTTPD_SERVER_CERT_PEM_ESCAPED=`escapePath ${HTTPD_SERVER_CERT_PEM}`
  HTTPD_SERVER_KEY_PEM_ESCAPED=`escapePath ${HTTPD_SERVER_KEY_PEM}`
  HTTPD_SERVER_CERT_CHAIN_PEM_ESCAPED=`escapePath ${HTTPD_SERVER_CERT_CHAIN_PEM}`
  
  ${SED} -e "s/%SERVER_FQDN%/${SERVER_FQDN}/g" -e "s/%TOMCAT_HTTPS_PORT%/${TOMCAT_HTTPS_PORT}/g" -e "s/%HTTPD_SERVER_CERT_PEM%/${HTTPD_SERVER_CERT_PEM_ESCAPED}/g" -e "s/%HTTPD_SERVER_KEY_PEM%/${HTTPD_SERVER_KEY_PEM_ESCAPED}/g"   -e "s/%HTTPD_SERVER_CERT_CHAIN_PEM%/${HTTPD_SERVER_CERT_CHAIN_PEM_ESCAPED}/g"   -e "s/%OPENAM_DEPLOYMENT_URI%/${OPENAM_DEPLOYMENT_URI}/g"  ${INSTALL_SCRIPTS_BASE}/templates/httpd-server.conf.TEMPLATE > ${HTTPD_SERVER_CUSTOM_CONF}

}

#---------------------------------------------
# Main
#---------------------------------------------
generateServerCert
generateServerCertChain
modifyHttpdConfig
stopHttpd
startHttpd




