#!/bin/bash 

. ./platform.properties
. ./functions
. ./functions-opendj

#---------------------------------------------
installOpenDJ() {
#---------------------------------------------

  checkBaseDir
  exitIfRCFailure

  if [ ! -d ${OPENDJ_BASE} ]; then
    ${MKDIR} ${OPENDJ_BASE}
    if [ $? != 0 ]; then
      printf "ERROR: Error creating OpenDJ base directory ${OPENDJ_BASE}. Aborting.\n"
      exitFailure
    fi
  fi

  ${UNZIP} -q ${OPENDJ_ZIP} -d ${OPENDJ_BASE}
  if [ $? != 0 ]; then
    printf "ERROR: Error unzipping the OpenDJ software ${OPENDJ_ZIP} in directory ${OPENDJ_BASE}. Aborting.\n"
    exitFailure
  else
    printf "INFO: Successfully unzipped the OpenDJ software in directory ${OPENDJ_BASE}.\n"
  fi 

  # Move opendj/opendj to just opendj
  TOPDIRDS=`ls ${OPENDJ_BASE}`
  ${MV} ${OPENDJ_BASE}/${TOPDIRDS}/* ${OPENDJ_BASE}
  if [ $? != 0 ]; then
    printf "ERROR: Cannot move ${OPENDJ_BASE}/${TOPDIRDS}/* to ${OPENDJ_BASE}. Aborting.\n"
    exitFailure
  fi

  echo "INFO: Installing OpenDJ ..."
  CURDIR=`pwd`
  cd ${OPENDJ_BASE}
  SETUP=${OPENDJ_BASE}/setup
  if [ ! -f ${SETUP} ]; then
    printf "ERROR: Script ${SETUP} does not exist. Someting must have gone wrong. Aborting.\n"
    exitFailure
  fi
  export JAVA_HOME
  ${SETUP} --cli --no-prompt -b ${OPENDJ_SUFFIX} -a -p ${OPENDJ_LDAP_PORT} --adminConnectorPort ${OPENDJ_ADMIN_PORT} -D ${OPENDJ_ADMIN} -w ${OPENDJ_ADMIN_PASSWORD} -O --acceptLicense
  if [ $? != 0 ]; then
    printf "ERROR: OpenDJ setup failed. Aborting.\n"
    exitFailure
  else
    printf "INFO: Successfully installed OpenDJ with LDAP port ${OPENDJ_LDAP_PORT} and suffix ${OPENDJ_SUFFIX}.\n"
  fi
  cd ${CURDIR}
}

#---------------------------------------------
# Main
#---------------------------------------------
installOpenDJ

