#!/bin/bash 

. ./platform.properties
. ./functions
. ./functions-tomcat
. ./functions-openam

#---------------------------------------------
removeOpenAMFiles() {
#---------------------------------------------
  if [ ! -z ${OPENAM_BASE} ]; then
    ${RM} -rf ${OPENAM_BASE}
    if [ $? != 0 ]; then
      printf "ERROR: Error removing data in OpenAM base directory ${OPENAM_BASE}. Aborting.\n"
    else
      printf "INFO: Successfully removed OpenAM files from directory ${OPENAM_BASE}.\n"
    fi 
  fi
}

#---------------------------------------------
removeOpenAMWebApplication() {
#---------------------------------------------
  DEPLOY_DIR=${TOMCAT_WEBAPPS_DIR}/${OPENAM_DEPLOYMENT_URI}
  if [ ! -z ${DEPLOY_DIR} ]; then
    ${RM} -rf ${DEPLOY_DIR}
    if [ $? != 0 ]; then
      printf "ERROR: Error removing OpenAM web application from Tomcat (base directory is ${DEPLOY_DIR}). Aborting.\n"
    else
      printf "INFO: Successfully removed OpenAM web application from Tomcat.\n"
    fi 
  fi
}

#---------------------------------------------
# Main
#---------------------------------------------
removeOpenAMWebApplication
removeOpenAMFiles

