#!/bin/bash

. ./platform.properties
. ./functions
. ./functions-openam

#----------------------------------------------------------
configurePCookieAuthentication() {
#----------------------------------------------------------
  printf "INFO: Configuring persistent cookie authentication module and post authentication class.\n"
  ${SED} -e "s/%OPENAM_BASE_REALM%/${OPENAM_BASE_REALM}/g" -e "s/%PCOOKIE_AUTH_CHAIN%/${PCOOKIE_AUTH_CHAIN}/g" -e "s/%PCOOKIE_AUTH_MODULE%/${PCOOKIE_AUTH_MODULE}/g" ${INSTALL_SCRIPTS_BASE}/templates/openam-pcookie-batch.TEMPLATE > ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.ssoadm
  if [ $? != 0 ]; then
    printf "ERROR: Error using SED (${SED}).\n"
    returnFailure
  fi
  
 ${OPENAM_SSOADM} do-batch -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --batchfile ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.ssoadm --continue --batchstatus ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.STATUS
  if [ $? != 0 ]; then
    printf "ERROR: Error setting up the persistent cookie authentication module and post authentication class. See ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.STATUS for ssoadm return codes.\n"
  else
    printf "INFO: Successfully configured the persistent cookie authentication module and post authentication class.\n"
  fi
}

#----------------------------------------------------------
removePCookieAuthentication() {
#----------------------------------------------------------
  printf "INFO: Removing persistent cookie authentication module and post authentication class.\n"
  ${SED} -e "s/%OPENAM_BASE_REALM%/${OPENAM_BASE_REALM}/g" -e "s/%PCOOKIE_AUTH_CHAIN%/${PCOOKIE_AUTH_CHAIN}/g" -e "s/%PCOOKIE_AUTH_MODULE%/${PCOOKIE_AUTH_MODULE}/g" ${INSTALL_SCRIPTS_BASE}/templates/openam-pcookie-batch-remove.TEMPLATE > ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch-remove.ssoadm
  if [ $? != 0 ]; then
    printf "ERROR: Error using SED (${SED}).\n"
    returnFailure
  fi
  
 ${OPENAM_SSOADM} do-batch -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --batchfile ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch-remove.ssoadm --continue --batchstatus ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch-remove.STATUS
  if [ $? != 0 ]; then
    printf "ERROR: Error removing the persistent cookie authentication module and post authentication class. See ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch-remove.STATUS for ssoadm return codes.\n"
  else
    printf "INFO: Successfully removed the persistent cookie authentication module and post authentication class.\n"
  fi
}

#---------------------------------------------
# Main
#---------------------------------------------
printScriptStart
if [ $# == 1 ] && [ $1 == "remove" ]; then
  printf "INFO: Mode is REMOVE.\n"
  removePCookieAuthentication
else
  configurePCookieAuthentication
fi
printScriptEnd
