#!/bin/bash

. ./platform.properties
. ./functions
. ./functions-tomcat
. ./functions-openam

OPENAM_PCOOKIE_CLASS=org.forgerock.tinker.authentication.modules.persistentcookie.PersistentCookieAuthModule

#----------------------------------------------------------
configurePCookieAuthentication() {
#----------------------------------------------------------
  printf "INFO: Configuring persistent cookie authentication module and post authentication class.\n"
  ${SED} -e "s/%OPENAM_BASE_REALM%/${OPENAM_BASE_REALM}/g" -e "s/%PCOOKIE_AUTH_CHAIN%/${PCOOKIE_AUTH_CHAIN}/g" -e "s/%PCOOKIE_AUTH_MODULE%/${PCOOKIE_AUTH_MODULE}/g"  -e "s/%OPENAM_PCOOKIE_CLASS%/${OPENAM_PCOOKIE_CLASS}/g" ${INSTALL_SCRIPTS_BASE}/templates/openam-pcookie-batch.TEMPLATE > ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.ssoadm
  if [ $? != 0 ]; then
    printf "ERROR: Error using SED (${SED}).\n"
    returnFailure
  fi
  
 ${OPENAM_SSOADM} do-batch -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --batchfile ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.ssoadm --continue --batchstatus ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.STATUS
  if [ $? != 0 ]; then
    printf "ERROR: Error setting up the persistent cookie authentication module and post authentication class. See ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.STATUS for ssoadm return codes.\n"
  else
    printf "INFO: Successfully configured the persistent cookie authentication module and post authentication class.\n"
  fi
}

#----------------------------------------------------------
removePCookieAuthentication() {
#----------------------------------------------------------
  printf "INFO: Removing persistent cookie authentication module and post authentication class.\n"
  ${SED} -e "s/%OPENAM_BASE_REALM%/${OPENAM_BASE_REALM}/g" -e "s/%PCOOKIE_AUTH_CHAIN%/${PCOOKIE_AUTH_CHAIN}/g" -e "s/%PCOOKIE_AUTH_MODULE%/${PCOOKIE_AUTH_MODULE}/g" -e "s/%OPENAM_PCOOKIE_CLASS%/${OPENAM_PCOOKIE_CLASS}/g" ${INSTALL_SCRIPTS_BASE}/templates/openam-pcookie-batch-remove.TEMPLATE > ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch-remove.ssoadm
  if [ $? != 0 ]; then
    printf "ERROR: Error using SED (${SED}).\n"
    returnFailure
  fi
  
 ${OPENAM_SSOADM} do-batch -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --batchfile ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch-remove.ssoadm --continue --batchstatus ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch-remove.STATUS
  if [ $? != 0 ]; then
    printf "ERROR: Error removing the persistent cookie authentication module and post authentication class. See ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch-remove.STATUS for ssoadm return codes.\n"
  else
    printf "INFO: Successfully removed the persistent cookie authentication module and post authentication class.\n"
  fi
}

#----------------------------------------------------------
buildClasspath() {
#----------------------------------------------------------
  # Add the OpenAM JAR files
  for i in `ls ${OPENAM_WEBAPP_DIR}/WEB-INF/lib/*.jar`
  do
    CLASSPATH=${CLASSPATH}:$i
  done

  # Add the Tomcat JAR files
  for i in `ls ${TOMCAT_LIB_DIR}/*.jar`
  do
    CLASSPATH=${CLASSPATH}:$i
  done

  #echo "CLASSPATH=${CLASSPATH}"
}


#----------------------------------------------------------
compileJava() {
#----------------------------------------------------------
# Compile the Java sources
# This should be done using ant once approved to run on INT
#
  CURDIR=`pwd`
  cd openam-custom
  for src_file in `find . -name *.java`
  do
    printf "=====================================================================\n"
    printf "*** Compiling ${src_file}\n"
    ${JAVA_HOME}/bin/javac -classpath ${CLASSPATH} ${src_file} -d ${OPENAM_CLASSES_DIR}
    if [ "$?" -ne "0" ]; then
        echo "*** Error: During compilation"
        exit
    fi
  done
  cd ${CURDIR}
}

#---------------------------------------------
# Main
#---------------------------------------------
printScriptStart
if [ $# == 1 ] && [ $1 == "remove" ]; then
  printf "INFO: Mode is REMOVE.\n"
  removePCookieAuthentication
else
  buildClasspath
  compileJava
  configurePCookieAuthentication
fi
stopTomcat
startTomcat
printScriptEnd
