#!/bin/bash

. ./platform.properties
. ./functions
#. ./functions-tomcat
. ./functions-openam

#----------------------------------------------------------
enableStatelessSessions() {
#----------------------------------------------------------

  SIGN_ALGO=HS512

  printf "INFO: Setting signing algorithm for stateless sessions to ${SIGN_ALGO}.\n"
  ${OPENAM_SSOADM} set-attr-defs  -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --servicename iPlanetAMSessionService -t global --attributevalues openam-session-stateless-signing-type=${SIGN_ALGO}
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    returnFailure
  fi

  printf "INFO: Enabling stateless sessions for realm ${OPENAM_BASE_REALM}.\n"
  ${OPENAM_SSOADM} set-realm-svc-attrs -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --realm ${OPENAM_BASE_REALM} --servicename iPlanetAMAuthService --attributevalues openam-auth-stateless-sessions=true
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    returnFailure
  fi

  printRealmAuthAttributes

  # ${SED} -e "s/%OPENAM_BASE_REALM%/${OPENAM_BASE_REALM}/g" -e "s/%PCOOKIE_AUTH_CHAIN%/${PCOOKIE_AUTH_CHAIN}/g" -e "s/%PCOOKIE_AUTH_MODULE%/${PCOOKIE_AUTH_MODULE}/g"  -e "s/%OPENAM_PCOOKIE_CLASS%/${OPENAM_PCOOKIE_CLASS}/g" ${INSTALL_SCRIPTS_BASE}/templates/openam-pcookie-batch.TEMPLATE > ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.ssoadm
  #if [ $? != 0 ]; then
  #  printf "ERROR: Error using SED (${SED}).\n"
  #  returnFailure
  #fi
  
  #${OPENAM_SSOADM} do-batch -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --batchfile ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.ssoadm --continue --batchstatus ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.STATUS
  #if [ $? != 0 ]; then
  #  printf "ERROR: Error setting up the persistent cookie authentication module and post authentication class. See ${INSTALL_SCRIPTS_BASE}/openam-pcookie-batch.STATUS for ssoadm return codes.\n"
  #else
  #  printf "INFO: Successfully configured the persistent cookie authentication module and post authentication class.\n"
  #fi
}

#----------------------------------------------------------
disableStatelessSessions() {
#----------------------------------------------------------
  printf "INFO: Disabling stateless sessions for realm ${OPENAM_BASE_REALM}.\n"
  ${OPENAM_SSOADM} set-realm-svc-attrs -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --realm ${OPENAM_BASE_REALM} --servicename iPlanetAMAuthService --attributevalues openam-auth-stateless-sessions=false
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    returnFailure
  fi

  printRealmAuthAttributes
}

#----------------------------------------------------------
printRealmAuthAttributes() {
#----------------------------------------------------------
  printf "INFO: Listing realm authentication service attributes for realm ${OPENAM_BASE_REALM}.\n"
  ${OPENAM_SSOADM} get-realm-svc-attrs -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --realm ${OPENAM_BASE_REALM} --servicename iPlanetAMAuthService 
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    returnFailure
  fi
}

#---------------------------------------------
# Main
#---------------------------------------------
printScriptStart
if [ $# == 1 ] && [ $1 == "remove" ]; then
  printf "INFO: Mode is REMOVE.\n"
  disableStatelessSessions
else
  enableStatelessSessions
fi
#stopTomcat
#startTomcat
printScriptEnd
