#!/bin/bash

. ./platform.properties
. ./functions
. ./functions-tomcat
. ./functions-openam

#----------------------------------------------------------
configureCustomDevicePrintAuthentication() {
#----------------------------------------------------------
  printf "INFO: Configuring custom device print realm, authentication module and chain.\n"

  ${SED} -e "s/%OPENAM_CUSTOM_DEVICEPRINT_REALM%/${OPENAM_CUSTOM_DEVICEPRINT_REALM}/g" -e "s/%OPENAM_CUSTOM_DEVICEPRINT_CHAIN%/${OPENAM_CUSTOM_DEVICEPRINT_CHAIN}/g" -e "s/%OPENAM_CUSTOM_DEVICEPRINT_MATCH_MODULE%/${OPENAM_CUSTOM_DEVICEPRINT_MATCH_MODULE}/g"  -e "s/%OPENAM_CUSTOM_DEVICEPRINT_SAVE_MODULE%/${OPENAM_CUSTOM_DEVICEPRINT_SAVE_MODULE}/g" ${INSTALL_SCRIPTS_BASE}/templates/openam-custom-deviceprint-batch.TEMPLATE > ${INSTALL_SCRIPTS_BASE}/openam-custom-deviceprint-batch.ssoadm
  if [ $? != 0 ]; then
    printf "ERROR: Error using SED (${SED}).\n"
    returnFailure
  fi
  
 ${OPENAM_SSOADM} do-batch --debug -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --batchfile ${INSTALL_SCRIPTS_BASE}/openam-custom-deviceprint-batch.ssoadm --continue --batchstatus ${INSTALL_SCRIPTS_BASE}/openam-custom-deviceprint-batch.STATUS
  if [ $? != 0 ]; then
    printf "ERROR: Error configuring custom device print realm, authentication module and chain. See ${INSTALL_SCRIPTS_BASE}/openam-custom-deviceprint-batch.STATUS for ssoadm return codes.\n"
  else
    printf "INFO: Successfully configured custom device print realm, authentication module and chain.\n"
  fi
}

#----------------------------------------------------------
configureScriptedModule() {
#----------------------------------------------------------
  printf "INFO: Configuring scripted authentication module.\n"
  ${OPENAM_SSOADM} update-auth-instance -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --realm ${OPENAM_CUSTOM_DEVICEPRINT_REALM} --name ${OPENAM_CUSTOM_DEVICEPRINT_MATCH_MODULE} --attributevalues iplanet-am-auth-scripted-client-script-enabled=false iplanet-am-auth-scripted-script-type='JavaScript' iplanet-am-auth-scripted-server-script-file=`pwd`/templates/openam-telephonenumber-deviceprint-serverscript.js
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: Error configuring scripted authentication module. ssoadm returned ${RC}.\n"
  else
    printf "INFO: Successfully configured scripted authentication module.\n"
  fi
}

#----------------------------------------------------------
removeCustomDevicePrintAuthentication() {
#----------------------------------------------------------
  # Remove the realm
  printf "INFO: Removing realm ${OPENAM_CUSTOM_DEVICEPRINT_REALM}.\n"
  ${OPENAM_SSOADM} delete-realm -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --realm ${OPENAM_CUSTOM_DEVICEPRINT_REALM}
  if [ $? != 0 ]; then
    printf "ERROR: Error removing realm ${OPENAM_CUSTOM_DEVICEPRINT_REALM}.\n"
  else
    printf "INFO: Successfully removed realm ${OPENAM_CUSTOM_DEVICEPRRINT_REALM}.\n"
  fi
}

#---------------------------------------------
# Main
#---------------------------------------------
printScriptStart
if [ $# == 1 ] && [ $1 == "remove" ]; then
  printf "INFO: Mode is REMOVE.\n"
  removeCustomDevicePrintAuthentication
else
  configureCustomDevicePrintAuthentication
  configureScriptedModule
fi
stopTomcat
startTomcat
printScriptEnd

