#!/bin/bash

. ./platform.properties
. ./functions
. ./functions-openam

#---------------------------------------------
checkRestAuthCallbacks() {
#---------------------------------------------
  USER=$1
  PASSWORD=$2

  #REST_AUTH_URL=https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/authenticate?realm=/${OPENAM_CUSTOM_DEVICEPRINT_REALM}\&noSession=true
  REST_AUTH_URL=https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/authenticate?realm=/${OPENAM_CUSTOM_DEVICEPRINT_REALM}

  # --------------------------------------------------------------------------------
  #
  # First connect to the endpoint to get the callback (no username or password)
  #
  # --------------------------------------------------------------------------------
  printf "=============================================================\n"
  printf "INFO: [Step 1] Get authentication callbacks and JWT Token ...\n"
  printf "=============================================================\n"
  #CURL_CMD1="${CURL} -s --insecure --request POST --header \"Content-Type: application/json\" ${REST_AUTH_URL}"
  #printf "INFO: [Request] ${CURL_CMD}\n"dd
  #RES1=`${CURL_CMD1}`
  RES1=`${CURL} -s --insecure --request POST --header \"Content-Type: application/json\" ${REST_AUTH_URL}`
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES1}\n"
  fi
  JWT_TOKEN=`echo ${RES1} | /opt/misc/jq --raw-output '.authId'`
  printf "INFO: JWT token is ${JWT_TOKEN}\n"

  # --------------------------------------------------------------------------------
  #
  # Second send in the credentials as required by the callbacks (DataStore)
  #
  # --------------------------------------------------------------------------------
  printf "=============================================================\n"
  printf "INFO: [Step 2] Authentication via REST (callbacks) as ${USER} ...\n"
  printf "=============================================================\n"
  #Working with module DataStore  
  RES2=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "DataStore1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "'${USER}'" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "changeit" } ] } ] }' ${REST_AUTH_URL}`
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES2}\n"
  fi

  printf "\n"

  # --------------------------------------------------------------------------------
  #
  # Third send in the credentials as required by the DeviceID (Match)
  #
  # --------------------------------------------------------------------------------
  printf "=============================================================\n"
  printf "INFO: [Step 3] Provide callbacks for the custom telephoneNumber (Match) module ...\n"
  printf "=============================================================\n"

  # Generate the device fingerprint data (e.g. from a template)
  ${SED} -e "s/%AUTHID%/${JWT_TOKEN}/g" -e "s/%TELEPHONENUMBER%/${OPENAM_CUSTOM_DEVICEPRINT_SAMPLE_TELEPHONENUMBER}/g" templates/telephoneNumber-deviceprint.json.TEMPLATE > telephoneNumber-deviceprint.json

  # Working with scripted module
  RES3=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data @telephoneNumber-deviceprint.json "${REST_AUTH_URL}"`

  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES3}\n"
  fi
  SSO_TOKEN=`echo ${RES3} | /opt/misc/jq --raw-output '.tokenId'`

  if [ ! -z ${SSO_TOKEN} ] && [ ${SSO_TOKEN} != "null" ]; then
    printf "INFO: Authentication successful. No need for further modules.\n"
    printf "INFO: SSO token is ${SSO_TOKEN}\n"
    exit 0
  else
    printf "INFO: DevideId (Match) does not trust device. Will continue with next module.\n"
  fi

  # --------------------------------------------------------------------------------
  #
  # Forth send in the credentials as required by LDAP module (2nd factor)
  #
  # --------------------------------------------------------------------------------
  printf "=============================================================\n"
  printf "INFO: [Step 4] Authentication via REST (callbacks) as ${USER} ...\n"
  printf "=============================================================\n"
  #Working with module LDAP
  RES4=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "LDAP1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "'${USER}'" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "'${PASSWORD}'" } ] } ] }' ${REST_AUTH_URL}`

  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES4}\n"
  fi
  SSO_TOKEN=`echo ${RES4} | /opt/misc/jq --raw-output '.tokenId'`
  if [ ! -z ${SSO_TOKEN} ] && [ ${SSO_TOKEN} != "null" ]; then
    printf "INFO: Authentication successful. No need for further modules.\n"
    printf "INFO: SSO token is ${SSO_TOKEN}\n"
    exit 0
  else
    CALLBACKS=`echo ${RES4} | /opt/misc/jq --raw-output '.callbacks'`
    if [ ! -z "${CALLBACKS}" ] && [ "${CALLBACKS}" != "null" ]; then
      printf "INFO: Callbacks returned. Assuming this is to get consent to store the device permanently.\n"
    else
      printf "INFO: Authentication failed.\n"
      exit 1
    fi		
  fi

  # --------------------------------------------------------------------------------
  #
  # Fifth send the consent to store the trusted device information 
  #
  # --------------------------------------------------------------------------------
  printf "=============================================================\n"
  printf "INFO: [Step 5] Consent to store the trusted device information  ...\n"
  printf "=============================================================\n"
  #Working with module DeviceId Save
  #value = 1 means that the profile should be stored
  RES5=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "DeviceSave2", "callbacks": [ { "type": "ChoiceCallback", "input": [ { "name": "IDToken1", "value": "0" } ] } ] }' ${REST_AUTH_URL}`

  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES5}\n"
  fi
  SSO_TOKEN=`echo ${RES5} | /opt/misc/jq --raw-output '.tokenId'`
  if [ ! -z ${SSO_TOKEN} ] && [ ${SSO_TOKEN} != "null" ]; then
    printf "INFO: Authentication successful. No need for further modules.\n"
    printf "INFO: SSO token is ${SSO_TOKEN}\n"
    exit 0
  else
    CALLBACKS=`echo ${RES5} | /opt/misc/jq --raw-output '.callbacks'`
    if [ ! -z "${CALLBACKS}" ] && [ "${CALLBACKS}" != "null" ]; then
      printf "INFO: Callbacks returned. Assuming this is to get the name under which the device should be stored.\n"
    else
      printf "INFO: Authentication failed.\n"
      exit 1
    fi		
  fi

  # --------------------------------------------------------------------------------
  #
  # Sixth send the name under which the device profile shall be stored
  #
  # --------------------------------------------------------------------------------
  printf "=============================================================\n"
  printf "INFO: [Step 6] Provide the name under which the device profile shall be stored  ...\n"
  printf "=============================================================\n"
  #Working with module DeviceId Save
  #If the device name is empry, il will be generated
  RES6=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "DeviceIdSave3", "callbacks": [ { "type": "NameCallback", "input": [ { "name": "IDToken1", "value": "" } ] } ] }' ${REST_AUTH_URL}`

  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES5}\n"
  fi
  SSO_TOKEN=`echo ${RES6} | /opt/misc/jq --raw-output '.tokenId'`
  if [ ! -z ${SSO_TOKEN} ] && [ ${SSO_TOKEN} != "null" ]; then
    printf "INFO: Authentication successful. No need for further modules.\n"
    printf "INFO: SSO token is ${SSO_TOKEN}\n"
    exit 0
  else
    printf "INFO: Authentication failed.\n"
    exit 1
  fi

}

#---------------------------------------------
authLDAP() {
#---------------------------------------------
  USER=$1
  PASSWORD=$2

  REST_AUTH_URL=https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/authenticate?realm=/${OPENAM_CUSTOM_DEVICEPRINT_REALM}\&module=LDAP\&noSession=true\&authIndexType=module\&authIndexValue=LDAP

  printf "=============================================================\n"
  printf "INFO: Getting JWT_Token ...\n"
  printf "=============================================================\n"
  RES1=`${CURL} -s --insecure --request POST --header \"Content-Type: application/json\" ${REST_AUTH_URL}`
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES1}\n"
  fi
  JWT_TOKEN=`echo ${RES1} | /opt/misc/jq --raw-output '.authId'`
  printf "INFO: JWT token is ${JWT_TOKEN}\n"

  printf "=============================================================\n"
  printf "INFO: Authentication via REST (callbacks) as ${USER} against realm ${OPENAM_CUSTOM_DEVICEPRINT_REALM} and module LDAP...\n"
  printf "=============================================================\n"
  #Working with module LDAP
  RES4=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "LDAP1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "demo" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "'${PASSWORD}'" } ] } ] }' ${REST_AUTH_URL}`

  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES4}\n"
  fi
  SSO_TOKEN=`echo ${RES4} | /opt/misc/jq --raw-output '.tokenId'`
  printf "INFO: SSO token is ${SSO_TOKEN}\n"
}

#---------------------------------------------
authLDAP() {
#---------------------------------------------
  USER=$1
  PASSWORD=$2

  REST_AUTH_URL=https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/authenticate?realm=/${OPENAM_CUSTOM_DEVICEPRINT_REALM}\&module=LDAP\&noSession=true\&authIndexType=module\&authIndexValue=LDAP

  printf "=============================================================\n"
  printf "INFO: Getting JWT_Token ...\n"
  printf "=============================================================\n"
  RES1=`${CURL} -s --insecure --request POST --header \"Content-Type: application/json\" ${REST_AUTH_URL}`
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES1}\n"
  fi
  JWT_TOKEN=`echo ${RES1} | /opt/misc/jq --raw-output '.authId'`
  printf "INFO: JWT token is ${JWT_TOKEN}\n"

  printf "=============================================================\n"
  printf "INFO: Authentication via REST (callbacks) as ${USER} against realm ${OPENAM_CUSTOM_DEVICEPRINT_REALM} and module LDAP...\n"
  printf "=============================================================\n"
  #Working with module LDAP
  RES4=`${CURL} -s --insecure --request POST --header "Content-Type: application/json" --data '{ "authId": "'${JWT_TOKEN}'", "template": "", "stage": "LDAP1", "callbacks": [ { "type": "NameCallback", "output": [ { "name": "prompt", "value": " User Name: " } ], "input": [ { "name": "IDToken1", "value": "demo" } ] }, { "type": "PasswordCallback", "output": [ { "name": "prompt", "value": " Password: " } ], "input": [ { "name": "IDToken2", "value": "'${PASSWORD}'" } ] } ] }' ${REST_AUTH_URL}`

  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: ssoadm returned ${RC}.\n"
    exit 1
  else
    printf "INFO: [Response] ${RES4}\n"
  fi
  SSO_TOKEN=`echo ${RES4} | /opt/misc/jq --raw-output '.tokenId'`
  printf "INFO: SSO token is ${SSO_TOKEN}\n"
}

#---------------------------------------------
# Main
#---------------------------------------------
checkRestAuthCallbacks demo changeit
#authLDAP

