#!/bin/bash -x

. ./platform.properties
. ./functions
. ./functions-openam

. ./651-authz-base

#---------------------------------------------
listSubjects() {
#---------------------------------------------
  REALM=$1

  SSO_TOKEN=`authAdmin`

  printf "INFO: Listing users for realm ${REALM} ...\n"
  URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/${REALM}/users?_queryFilter=true&_prettyPrint=true"
  RES=`${CURL} -s --insecure --request GET --header "iPlanetDirectoryPro: ${SSO_TOKEN}" --header "Content-Type: application/json" "${URL}"`
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: curl returned ${RC}.\n"
    return 1
  else
    printf "INFO:\n[Response]\n${RES}\n"
  fi

  printf "INFO: Listing groups for realm ${REALM} ...\n"
  URL="https://${SERVER_FQDN}:443/${OPENAM_DEPLOYMENT_URI}/json/${REALM}/groups?_queryFilter=true&_prettyPrint=true"
  RES=`${CURL} -s --insecure --request GET --header "iPlanetDirectoryPro: ${SSO_TOKEN}" --header "Content-Type: application/json" "${URL}"`
  RC=$?
  if [ ${RC} != 0 ]; then
    printf "ERROR: curl returned ${RC}.\n"
    return 1
  else
    printf "INFO:\n[Response]\n${RES}\n"
  fi
}
listSubjects ${OPENAM_AUTHZ_REALM}
