#!/bin/bash 

. ./platform.properties
. ./functions
#. ./functions-tomcat
. ./functions-openam

#----------------------------------------------------------
createIDPMetadataFiles() {
#----------------------------------------------------------
  # Create template
  printf "INFO: Creating WS-Federation metadata templates.\n"
  ${OPENAM_SSOADM} create-metadata-templ -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --entityid ${OPENAM_MS_IDP_ENTITYID_WSFED} --identityprovider ${OPENAM_MS_IDP_METAALIAS_WSFED} --meta-data-file ${OPENAM_MS_IDP_META_WSFED} --extended-data-file  ${OPENAM_MS_IDP_META_EXTENDED_WSFED} --idpscertalias test --spec wsfed

  printf "INFO: Creating SAML2 metadata templates.\n"
  ${OPENAM_SSOADM} create-metadata-templ -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --entityid ${OPENAM_MS_IDP_ENTITYID_SAML} --identityprovider ${OPENAM_MS_IDP_METAALIAS_SAML} --meta-data-file ${OPENAM_MS_IDP_META_SAML} --extended-data-file  ${OPENAM_MS_IDP_META_EXTENDED_SAML} --idpscertalias test --spec saml2

  if [ $? != 0 ]; then
    printf "ERROR: Error creating metadata template.\n"
  else
    printf "INFO: Successfully created metadata template.\n"
  fi
}

#----------------------------------------------------------
createMetadataTemplateWsfed() {
#----------------------------------------------------------
  # Create template
  printf "INFO: Creating WS-Federation metadata templates.\n"
  ${OPENAM_SSOADM} create-metadata-templ -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --entityid "${MS_SP_ENTITYID_SAML}" --serviceprovider spwsfed --meta-data-file spwsfed-meta.xml --extended-data-file  spwsfed-extended.xml --spec wsfed

  if [ $? != 0 ]; then
    printf "ERROR: Error creating metadata template.\n"
  else
    printf "INFO: Successfully created metadata template.\n"
  fi
}

#----------------------------------------------------------
createCOT() {
#----------------------------------------------------------
  REALM=$1

  # Create circle of trust
  printf "INFO: Creating circle of trust.\n"
  ${OPENAM_SSOADM} create-cot -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --realm ${REALM} --cot ${OPENAM_MS_COT}

  if [ $? != 0 ]; then
    printf "ERROR: Error creating circle of trust.\n"
  else
    printf "INFO: Successfully created circle of trust.\n"
  fi
}

#----------------------------------------------------------
importIDPMetadata() {
#----------------------------------------------------------
  REALM=$1

  # Create template
  printf "INFO: Importing WS-Federation metadata.\n"
  ${OPENAM_SSOADM} import-entity --realm ${REALM} -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --meta-data-file ${OPENAM_MS_IDP_META_WSFED} --extended-data-file ${OPENAM_MS_IDP_META_EXTENDED_WSFED} --spec wsfed --cot ${OPENAM_MS_COT} 

  printf "INFO: Importing SAML2 metadata.\n"
  ${OPENAM_SSOADM} import-entity --realm ${REALM} -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --meta-data-file ${OPENAM_MS_IDP_META_SAML} --extended-data-file  ${OPENAM_MS_IDP_META_EXTENDED_SAML} --cot ${OPENAM_MS_COT} --spec saml2

  if [ $? != 0 ]; then
    printf "ERROR: Error importing metadata.\n"
  else
    printf "INFO: Successfully imported metadata.\n"
  fi
}

#----------------------------------------------------------
#exportMetadata() {
#----------------------------------------------------------
#  REALM=$1
#
#  # Export entity
#  printf "INFO: Exporting WS-Federation metadata.\n"
#  ${OPENAM_SSOADM} export-entity --realm /${REALM} -u ${OPENAM_ADMIN} -f ${OPENAM_SSOADM_PASSFILE} --entityid wsfedidp --meta-data-file /tmp/meta.xml --extended-data-file /tmp/extended.xml --spec wsfed
#}


#---------------------------------------------
# Main
#---------------------------------------------
#createIDPMetadataFiles ${OPENAM_MS_REALM}
#createMetadataTemplateWsfed ${OPENAM_MS_REALM}
#createCOT ${OPENAM_MS_REALM}
importIDPMetadata ${OPENAM_MS_REALM}
#exportMetadata ${OPENAM_MS_REALM}
